{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}-srv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.typePort }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
{{- end }}
